name: Mark stale issues

on:
  schedule:
    - cron: '0 0 * * *'  # Läuft täglich um Mitternacht

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Mark stale issues
        uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 30
          days-before-close: 7
          stale-issue-message: "Diese Issue wurde als inaktiv markiert und wird bald geschlossen."
          close-issue-message: "Die Issue wurde geschlossen, da sie seit 7 Tagen inaktiv war."
